# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17b00e6fb91d9b5e621347eeac7d027880314b79a876b1123d75a2f98e64c3d9d6e7c507e9ff2c934970e0081c8018c7cb03db753a0afc1300c050752e0faee

test:
  secret_key_base: 482f22a7216b7032ba93975ddd5b02e185de0da774137483802cf31d0b269c1759bce84173243a6c50611da71f4b7b777f2833cd615dff53dfc06d7e81c433a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
